### ISSUE TITLE
Heatmap and table views are not visible when in mobile view

### ISSUE THREAD

**Issue by OyvindLGjesdal** [SemanticComputing/nimisampo.fi#2]
When I perform a search and scroll down to the facets for "table", "map_clusters", "map_markers" and "heatmaps", only "map_clusters" and "map_markers" show up. I can click between table and heatmaps, but the "button bar" is the bottom of the page.

Thanks for the work on nimisampo and the sampo-ui :-)

![Screenshot from 2020-08-25 15-20-02](https://user-images.githubusercontent.com/5328572/91179504-de9e3c00-e6e6-11ea-9a43-a323222ea827.png)

**Comment by esikkala** [comment]
Thanks for the bug report! This should be fixed with https://github.com/SemanticComputing/nimisampo.fi/commit/a1b1eb93a3d9211c601cbde5cdaa087505f47a32
